
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analysis;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int parc = 18;
  public static final int para = 17;
  public static final int cadena = 9;
  public static final int decimal = 7;
  public static final int pr_if = 10;
  public static final int pr_false = 13;
  public static final int pr_print = 11;
  public static final int por = 4;
  public static final int or = 16;
  public static final int pr_true = 14;
  public static final int menos = 3;
  public static final int div = 5;
  public static final int EOF = 0;
  public static final int id = 8;
  public static final int error = 1;
  public static final int entero = 6;
  public static final int llavec = 20;
  public static final int mas = 2;
  public static final int llavea = 19;
  public static final int igualigual = 15;
  public static final int and = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "por",
  "div",
  "entero",
  "decimal",
  "id",
  "cadena",
  "pr_if",
  "pr_print",
  "and",
  "pr_false",
  "pr_true",
  "igualigual",
  "or",
  "para",
  "parc",
  "llavea",
  "llavec"
  };
}

